### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by M-Anne-M** [aws-samples/amazon-sumerian-hosts#13]
There appears to be a memory leak somewhere in the new POI update.  It usually takes around 10 to 20 minutes for it to build up to 5GB of memory used in chrome, upon which it closes itself and gives the chrome "out of memory" error screen.  The only thing in the base code that I changed would be inputting my cognito ID.  To double check that it wasn't something with the new default hosts, I swapped them out with Wes and Fiona and got the same results.  Any help with finding where the leak is coming from is appreciated, thanks!

**Comment by c-morten** [comment]
Thank you for reporting this @M-Anne-M. I will try to reproduce and come up with a solution, I may reach out for more information.

**Comment by c-morten** [comment]
@M-Anne-M this should be fixed in version 1.3.1, please re-open if you continue to have issues after getting the latest release.
