### ISSUE TITLE
HOSTS_VERSION not defined while using three.js package

### ISSUE THREAD

**Issue by krithick** [aws-samples/amazon-sumerian-hosts#133]
says it has to be defined in the webpack , but what if i dont want to manage webpack or try to implement the package with react or some other framework
<img width="1280" alt="Screenshot 2022-06-30 at 2 48 35 PM" src="https://user-images.githubusercontent.com/34998488/176644877-dbde5bc7-4a46-4203-869a-c0090b80ac56.png">
.

**Comment by prestomation** [comment]
Hi Krithick. How are you importing and using this package? 

The package itself is built using webpack, but we do/should not require that applications that use this package use webpack.

**Comment by krithick** [comment]
Hi Preston , I was trying to use the node package instead of the build file for three.js just the like the Babylon examples in a react environment that is build to run three.js(Not react-drei). In other words trying to import  the host and other features from the npm package

**Comment by krithick** [comment]
On other note i cant import HOST from the build file like i used to do with the older version

> Hi Preston , I was trying to use the node package instead of the build file for three.js just the like the Babylon examples in a react environment that is build to run three.js(Not react-drei). In other words trying to import the host and other features from the npm package

**Comment by Krxtopher** [comment]
@krithick, can you provide a small GitHub repo that demonstrates how you're trying to incorporate the hosts node module into your code? I don't think we have a clear enough understanding of your project's structure and build process to be able to provide assistance without more detail. Thanks.

**Comment by prestomation** [comment]
@krithick Please try the recently released version v2.0.4. This should resolve the original `HOSTS_VERSION` issue.
