### ISSUE TITLE
Can't get past Loading...

### ISSUE THREAD

**Issue by rrjgithub** [aws-samples/amazon-sumerian-hosts#137]
I have install all modules and demo seems to start ok locally, but when I click on any of the demo links.. it shows Loading ... and doesn't go past that point. am I missing something? I installed all the modules. 

bash-3.2$ npm run start-babylon

> amazon-sumerian-hosts@ start-babylon /Users/xxx/workspace/amazon-sumerian-hosts
> cross-env ENGINE=babylon NODE_ENV=development webpack-dev-server

<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:8080/
<i> [webpack-dev-server] On Your Network (IPv4): http://xxx.xxx:8080/
<i> [webpack-dev-server] On Your Network (IPv6): http://xxx]:8080/
<i> [webpack-dev-server] Content not from webpack is served from '/Users/xxx/workspace/amazon-sumerian-hosts' directory
<i> [webpack-dev-middleware] wait until bundle finished: /packages/demos-babylon/src/
<i> [webpack-dev-middleware] wait until bundle finished: /packages/amazon-sumerian-hosts-babylon/test/integration_test/Babylon.js/
assets by path ./packages/demos-babylon/dist/*.js 26.3 MiB
  asset ./packages/demos-babylon/dist/customCharacterDemo.js 8.31 MiB [emitted] [minimized] (name: customCharacterDemo) 2 related assets
  asset ./packages/demos-babylon/dist/chatbotDemo.js 5.99 MiB [emitted] [minimized] (name: chatbotDemo) 2 related assets
  asset ./packages/demos-babylon/dist/gesturesDemo.js 5.99 MiB [emitted] [minimized] (name: gesturesDemo) 2 related assets
  asset ./packages/demos-babylon/dist/helloWorldDemo.js 5.99 MiB [emitted] [minimized] (name: helloWorldDemo) 2 related assets
assets by path ./packages/amazon-sumerian-hosts-babylon/ 22 MiB
  asset ./packages/amazon-sumerian-hosts-babylon/test/integration_test/Babylon.js/dist/animationTest.js 8.36 MiB [emitted] [minimized] (name: animationTest) 2 related assets
  asset ./packages/amazon-sumerian-hosts-babylon/test/integration_test/Babylon.js/dist/textToSpeechTest.js 8.36 MiB [emitted] [minimized] (name: textToSpeechTest) 2 related assets
  asset ./packages/amazon-sumerian-hosts-babylon/dist/host.babylon.js 5.27 MiB [emitted] [minimized] (name: host.babylon) 2 related assets
asset ./packages/amazon-sumerian-hosts-three/dist/host.three.js 249 KiB [emitted] [minimized] (name: host.three) 2 related assets
asset ./packages/amazon-sumerian-hosts-core/dist/host.core.js 240 KiB [emitted] [minimized] (name: host.core) 2 related assets
runtime modules 248 KiB 115 modules
javascript modules 12.5 MiB 1522 modules
json modules 2.81 MiB
  ./node_modules/aws-sdk/apis/metadata.json 15.9 KiB [built] [code generated]
  ./node_modules/aws-sdk/apis/sts-2011-06-15.min.json 3.71 KiB [built] [code generated]
  ./node_modules/aws-sdk/apis/sts-2011-06-15.paginators.json 27 bytes [built] [code generated]
  ./node_modules/aws-sdk/apis/cognito-identity-2014-06-30.min.json 7.4 KiB [built] [code generated]
  ./node_modules/aws-sdk/apis/cognito-identity-2014-06-30.paginators.json 155 bytes [built] [code generated]
  ./node_modules/aws-sdk/apis/acm-2015-12-08.min.json 5.13 KiB [built] [code generated]
  ./node_modules/aws-sdk/apis/acm-2015-12-08.paginators.json 161 bytes [built] [code generated]
  ./node_modules/aws-sdk/apis/acm-2015-12-08.waiters2.json 569 bytes [built] [code generated]
  ./node_modules/aws-sdk/apis/apigateway-2015-07-09.min.json 54.1 KiB [built] [code generated]
  ./node_modules/aws-sdk/apis/apigateway-2015-07-09.paginators.json 1.37 KiB [built] [code generated]
  ./node_modules/aws-sdk/apis/application-autoscaling-2016-02-06.min.json 6.63 KiB [built] [code generated]
  + 229 modules
webpack 5.72.0 compiled successfully in 73220 ms

**Comment by prestomation** [comment]
Sorry you're having problems rrjgithub. What error messages do you see in your browser's javascript console when you open these demos?

**Comment by rrjgithub** [comment]
Failed to load resource: the server cognito-identity.us-east-1.amazonaws.com/:1 responded with a status of 400 ()

Uncaught (in promise) CredentialsError: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1
    at constructor.extractError (json.js:52:27)
    at constructor.callListeners (sequential_executor.js:106:20)
...

I did set the demo-credentials.js with the configIdentityPoolId value and configured my credentials with aws configure

**Comment by rrjgithub** [comment]
this is resolved. thanks
