### ISSUE TITLE
LookAt, Gesture, and Emote samples?

### ISSUE THREAD

**Issue by roschler** [aws-samples/amazon-sumerian-hosts#14]
I cloned this repo locally and then used a full text indexing package on its contents.  I can't seem to find any samples that show how to use AWS scripting to do the following operations:

* Execute the Host component look-at feature (E.g.- look at camera)
* Execute the Host component gesture feature
* Execute the Host component emote feature

I need to be able to do these things from the new Preview Scripting environment, _not_ the legacy scripting environment or from a IDE provided state machine.  Where can I find sample code for these features?

**Comment by c-morten** [comment]
Hi @roschler. This makes Host functionality available to open source engines like three.js and Babylon.js, it is not compatible with the Sumerian engine as it already has hosts as a built-in feature. I would suggest reaching out to the AWS forums or Sumerian slack channel for help with the Sumerian scripting API:
https://forums.aws.amazon.com/forum.jspa?forumID=300
http://slack.sumerian.aws/

**Comment by roschler** [comment]
Thanks will do.  I thought this was a set of samples for AWS Sumerian native.  Sorry.  As far as the Slack goes, it's hit or miss over there.  Some weeks responses come reliably.  Other weeks, there are long periods with no answer.  I've been trying to get answers on how to do the three features I mentioned above off and on for 2 months now and still no luck.  The AWS "official" forums have, over the years, given me a response rate around 10% so it's just not worth the effort (i.e. - for every 10 posts I make I get one reply and not necessarily a helpful one).

**Comment by roschler** [comment]
@c-morten One other question.  Is there any reason that I should stick with Sumerian native over what this repo offers?  I have Three.js experience and I am _not_ using Lex.  Instead I do my own chat handling and I could easily switch to calling Polly directly because I already do that in other applications I have written.  Also, I don't intend to publish a Sumerian scene, instead I will be beaming a session over Twitch.

Is this repo stable?  Like I said, now that I understand what it does, thanks to your reply, I'm wondering if it's the better choice for me?

**Comment by c-morten** [comment]
The host functionality we offer here is at parity with what you'll find inside Sumerian, with the added benefit that you can use it with your own custom 3d content if you prefer. So the choice really depends on what other functionality you require. If all of the features you need outside of hosts have equivalents in three.js then the only benefit for using Sumerian would be the editor.

As far as stability goes, this is a new repository. We have tested quite a bit with our own assets but there's always the possibility for bugs once more people start using it since I'm sure it will be used in ways we hadn't originally considered. That being said, we monitor the issues and do our best to release fixes quickly when issues are reported. The npm package is versioned so it's always possible to get the a version you know to be working if a bug were to be introduced.

If you want to get up and running quickly to test this repository out, I would suggest cloning the repository and reading through the [Getting Started in three.js](https://github.com/aws-samples/amazon-sumerian-hosts#Getting-started-in-three.js) steps in the readme. The steps walk you through an example implementation in three.js and should give you a general understanding of the API. We provide the finished example in the examples folder, all you need to do to see it working is add a cognito ID with permissions for Polly and run it on a local server.

**Comment by roschler** [comment]
@c-morten **Excellent**, I will do that.  

What is the best sample for learning how to get the Host to look at another item realistically?  

For example, suppose a Host was standing face forward and looking at the camera, and I wanted them to look at another Host standing directly along side of them (i.e. - to the left of them, also facing the camera).  I don't want them turning completely sideways to face that other Host and thereby offer up only a profile view of themselves.  Instead, I would like that Host to turn their head and then somewhat angle their body to look at the other Host, instead of doing a full body turn to face them.  On the other extreme, I don't want them just facing the camera directly and just swiveling just their eyes to look at the other host.  How would I do this with the usual tweening?  

The overall context would be two Hosts facing the camera for a presentation, and one of them looking at the other in a natural manner when the other Host is speaking.  Like a pair of newscasters.

**Comment by c-morten** [comment]
The example we provide includes a basic look interaction. There are 2 hosts and when one speaks, the other will look at the speaker. It uses the same type of point of interest functionality that we have in Sumerian, so you'll see the head/neck and eyes rotate at different speeds and to different extents, and the eyelid and brows move along with the eyes.

If you wanted to take this further, you could add more animations for turning the body and either add another layer to the point of interest configuration to drive those animations (you can look at the existing configuration for details on what inputs are required) or trigger body rotation animations manually based on conditions you define in your script. Although we focus on lipsync, gestures and point of interest in the example, you can trigger an animation at any time using the [AnimationFeature](https://aws-samples.github.io/amazon-sumerian-hosts/core_AnimationFeature.html). [Mixamo ](https://www.mixamo.com/#/)is a great place to go for finding free to use animation content.

**Comment by roschler** [comment]
@c-morten Thanks again!  I'll check it out.  I hope it works better than the native Sumerian stuff though.  I haven't gotten that work, either via state machine step using the PointOfInterest action set to the other Host, or from Scripting by emitting a "<host ID>.setLookAtTarget" message on the system bus.  The Host just seems to look around at random places, sometimes the other host's feet, etc.

**Comment by c-morten** [comment]
No problem, hopefully this repository can be helpful to you. Please don't hesitate to submit issues here if you run into errors or things don't work as expected.

**Comment by roschler** [comment]
@c-morten I just installed the node.js package and set up a quick test.  Can you point me to a document that tells me how handle AWS credentials issues in a secure fashion?  Normally when I do my Polly/S3/DynamoDB/etc. AWS work, that activity occurs solely on the back-end server side so I'm working from the AWS credentials store on my server.  

But I assume the "three.html" sample is meant to be used in a typical browser, and therefore I don't want to keep my credentials information client side (i.e. - in the browser).  Is there a document that tells me what do do here?  I already have my Cognito Identity Pool ID from my Sumerian project.  But I thought that too was stored only on the server side but in this case on the AWS servers and not mine, and that the Cogito ID should _not_ be shown to the client?  Either way, is there a doc that tells me how to set up the AWS credentials and Cogito info properly in a secure manner to use the three.html sample in a browser?

**Comment by roschler** [comment]
@c-morten That did it, thanks!  Using the right animation path fixed my "lost in space" problem with the Host positioning.  I'm good to go now.

- Do you know where I can find a complete list of all the _emotes_ and all the _gestures_ for each character?

BTW, I can't shake the feeling that the animations in _Sumerian-Hosts/ThreeJS_ are smoother than in the _Sumerian_ canvas environment.  Also, the shading of the characters and the ambient lighting seems more pleasing and easier on the eye.  Have you found that to be true too?
