### ISSUE TITLE
Swap voices at real-time, for a host?

### ISSUE THREAD

**Issue by roschler** [aws-samples/amazon-sumerian-hosts#16]
@c-morten I need to swap voices for a host in real-time.  Looking at the code, the voice to host assignment happens during the `createHost()` call:
```
		// Set up text to speech
		const audioListener = new THREE.AudioListener();
		camera.add(audioListener);
		host.addFeature(HOST.aws.TextToSpeechFeature, false, {
			listener: audioListener,
			attachTo: audioAttachJoint,
			voice,
			engine,
		});
```

Is there a way to change the voice on-the-fly, after the scene initialization and creation has occurred?

**Comment by c-morten** [comment]
Yes. Each time you use the play method to play a speech, you have the option to pass a configuration object as a second parameter. The configuration object supports the same parameters as the Polly API's [synthesizeSpeech](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Polly.html#synthesizeSpeech-property) method. So if you wanted to change the voice, you would pass an object that looks something like this as the second parameter to play: `{VoiceId: "Joanna"}`. This will update the voice for all of the speeches the host plays.

**Comment by roschler** [comment]
Thanks again @c-morten .  That's perfect. :)
