### ISSUE TITLE
LexRuntimeV2 recognizeUtterance Response

### ISSUE THREAD

**Issue by sckhg1367** [aws-samples/amazon-sumerian-hosts#167]
I use the recognizeUtterance function of LexRuntimeV2. But put the inputTranscript of Response into Base64 decoder and display "not a Base64 encoded string". I want to get the 'text of inputTranscript'(chinese). Please let me know if I did something wrong, thank you.

 
The execution screen is as follows:
<img width="605" alt="image" src="https://user-images.githubusercontent.com/63298370/223405117-92a3fc2d-bbd1-4d55-95a2-d883a60f3c23.png">

<img width="741" alt="image" src="https://user-images.githubusercontent.com/63298370/223405215-fca7559e-887f-43a7-b2d5-3c1c2b674013.png">

<img width="862" alt="image" src="https://user-images.githubusercontent.com/63298370/223405265-e0e4b4ad-85e0-45f4-9302-b4cb48a56bec.png">

<img width="694" alt="image" src="https://user-images.githubusercontent.com/63298370/223405328-06070ba7-27c1-408a-9e22-33623a28a7e6.png">

<img width="680" alt="image" src="https://user-images.githubusercontent.com/63298370/223405386-ea88fa13-96e1-4137-b44a-f8e34894446e.png">

**Comment by Krxtopher** [comment]
I maintain [a separate repository (personal) that contains the Amazon Sumerian Host Babylon demos](https://github.com/Krxtopher/sumerian-host-demos-babylonjs). As luck would have it, I *just* added a new "Lex v2" demo to that repository a few days ago. You can use that demo as a starting point for your Lex v2 Hosts application, or you can just look the [src/extras/LexV2Feature.js](https://github.com/Krxtopher/sumerian-host-demos-babylonjs/blob/main/src/extras/LexV2Feature.js) file for reference on how I'm decoding the Lex v2 response object. Look for the `decodeResponse(lexResponse)` and `decodeAndUnzipJsonString(encodedString)` functions in particular.

If that unblocks you, let us know so we can close this ticket. Thanks!

**Comment by sckhg1367** [comment]
@Krxtopher 
It's working, thank you~
