### ISSUE TITLE
Is there an event that fires when a host has completed an emote or a gesture?

### ISSUE THREAD

**Issue by roschler** [aws-samples/amazon-sumerian-hosts#17]
Is there an event I can hang a listener on or watch for in an interval timer that will tell me when a host has completed a gesture or an emote?

**Comment by c-morten** [comment]
Emotes and gestures are essentially just animations, so you can listen for events emitted from the AnimationFeature of a host to detect when a gesture or emote has ended. If you take a look at the API documentation for the [constructor ](https://aws-samples.github.io/amazon-sumerian-hosts/core_AnimationFeature.html)of the AnimationFeature you'll see a full list of the events supported. So if you had an instance of a host called 'host', you would want to listen to `host.AnimationFeature.EVENTS.stop` to detect when an animation finishes playing on that specific host instance. Alternatively you could listen to `HOST.anim.AnimationFeature.EVENTS.stop` to detect when an animation finishes playing on any host instance in the scene. The event will pass an object to your listener method with 2 properties: layerName and animationName. You can use these to check if the stop event is for the gesture or emote you're looking for. To see a working example of listening to local and global events, check inside the `main` function in the example file shortly after the hosts are initialized.

In addition, the playGesture method returns a promise object. So alternatively you could use promise.then syntax or asynchronous await to detect when a gesture or emote has ended.

**Comment by roschler** [comment]
Thanks @c-morten , many times.
