### ISSUE TITLE
Have host look at non-Host objects on the ThreeJS canvas with tweening?

### ISSUE THREAD

**Issue by roschler** [aws-samples/amazon-sumerian-hosts#18]
The _three.html_ sample shows how to make one host look at another:
```
host2.PointOfInterestFeature.setTarget(lookTracker1);
```
Can I make the host look at any other mesh object on a ThreeJS or perhaps in some arbitrary 3D vector, instead of at another host's look tracker location?  If so, is there a function call for this, hopefully one that handles that handles any necessary world coordinate translations, and one that also provides tweening so you get the same smooth look-at operation you get with the _PointOfInterestFeature.setTarget()_ call?

**Comment by c-morten** [comment]
For the three.js build, PointOfInterestFeature.setTarget will accept any object that is an instance of or inherits from the three.js [Object3D ](https://threejs.org/docs/#api/en/core/Object3D)class. This is the base class for objects that can be moved/rotated/scaled. The lookTracker objects we defined in the example are three.js Object3D objects that are generated when you import a glTF file and represent the skeleton of the character. 

While we don't currently support looking at a specific vector position, you could instead create an Object3D with no parent whose position is set to the position vector you want the host to focus on. That would result in the same thing as making the host look at a world space location. The tweening is actually defined by the maxSpeed properties defined in the options object that get passed to the PointOfInterestFeature constructor, so you would get the same type of tweening regardless of whether you choose to make the host look at an object created in our example or some other object you create.

**Comment by roschler** [comment]
@c-morten Perfect.  Will do.  Thanks again.
