### ISSUE TITLE
Quick way to stop ALL host text to speech?

### ISSUE THREAD

**Issue by roschler** [aws-samples/amazon-sumerian-hosts#22]
I want to be able to halt any and all hosts that are currently talking immediately.  What's the easiest way to do this?

**Comment by c-morten** [comment]
I think the easiest way to do this would be to maintain an array of any hosts that you instantiate. If you want all hosts to stop talking, loop through that array and execute the [stop](https://aws-samples.github.io/amazon-sumerian-hosts/AbstractTextToSpeechFeature.html#stop) method of the TextToSpeechFeature on each host in the array. This will stop any speech currently playing on each host.

**Comment by roschler** [comment]
Thanks.  That's what I ended up doing by looping through all the active hosts and calling that function.
