### ISSUE TITLE
Voice output in german does not work

### ISSUE THREAD

**Issue by r23** [aws-samples/amazon-sumerian-hosts#28]
Hello,

many thanks for the publication under Open Source

In the test environment the example works wonderfully with three.js.

Unfortunately I have problems with the conversion to German.

<speak>
  <amazon:domain name="conversational">
    <lang xml:lang="de-DE">
   Hallo, mein Name ist Vicki. Früher war ich nur Gastgeberin bei Amazon Sumerian, aber jetzt können Sie mich in anderen Javascript-Laufzeitumgebungen verwenden.
   </lang>
  </amazon:domain>
</speak>

.
.
.
        const voice1 = 'Vicki'; // Polly voice. Full list of available voices at: https://docs.aws.amazon.com/polly/latest/dg/voicelist.html
        const voiceEngine = ''; // Neural engine is not available for all voices in all regions: https://docs.aws.amazon.com/polly/latest/dg/NTTS-main.html

Unfortunately I have no more ideas how to switch the language output to German.

I am happy about tips and hints.

Ralf

**Comment by c-morten** [comment]
Hello @r23. Thanks for your interest in open source hosts! For changing the language output, you should be able to do this in the options object that can be passed when adding the TextToSpeechFeature. This feature gets added during Step 10 in the readme file, try using the following syntax to set the language to German:

host.addFeature(HOST.aws.TextToSpeechFeature, false, {
  listener: audioListener,
  attachTo: audioAttachJoint,
  voice,
  engine,
  language: “German”
});

You can find the available options for the TextToSpeechFeature in the API documentation for the constructor here: https://aws-samples.github.io/amazon-sumerian-hosts/AbstractTextToSpeechFeature.html. Keep in mind that only certain voices are supported for each language. You can find a table that maps the available languages to voices here: https://docs.aws.amazon.com/polly/latest/dg/voicelist.html.

**Comment by r23** [comment]
Hello @c-morten. 

Thank you very much for the quick answer. 

It works now.
https://blog.r23.de/wordpress-plugin-3d-charakter/
