### ISSUE TITLE
the first play have gestures, second play, just have voice, no gestures, must reload.

### ISSUE THREAD

**Issue by KISSMonX** [aws-samples/amazon-sumerian-hosts#29]
like title. 
if i want continue play gesture, must refresh page.
can someone help me fix it?

**Comment by KISSMonX** [comment]
anyone help?

**Comment by c-morten** [comment]
Hi @KISSMonX. Can I get some more information on how I can reproduce this issue? Are you using three.js or Babylon for the rendering engine? Also, are you using one of our provided example html files or a custom script?

**Comment by KISSMonX** [comment]
> Hi @KISSMonX. Can I get some more information on how I can reproduce this issue? Are you using three.js or Babylon for the rendering engine? Also, are you using one of our provided example html files or a custom script?

yes，i am using the provided example Babylon html，when the first play，Polly audio and gesture work fine。
but，second play(no refresh page)，just Polly audio，no guestures。 you can try it。thank you。

**Comment by KISSMonX** [comment]
#30  same.
