### ISSUE TITLE
walking/running hosts?

### ISSUE THREAD

**Issue by mikaelwozniak** [aws-samples/amazon-sumerian-hosts#32]
what is the best way to have those hosts walk from pointA to pointB, is there any motion animation provided here or in any other repo?

if not, what is the best recommended way to achieve this?

**Comment by c-morten** [comment]
Hi @mikaelwozniak. We don't include any navigation systems with the host API. Basically what you'd need to do is tween move/rotate the top level node that gets returned when you load your character glTF file, and then play animations along with that using the host's [AnimationFeature](https://aws-samples.github.io/amazon-sumerian-hosts/core_AnimationFeature.html). One good place to get animations from is [mixamo.com](https://www.mixamo.com/#/). This site will allow you to upload a character fbx file and retarget any animation from their library onto it and export the result as fbx. While we don't include fbx versions of our characters, you can import the provided glTF files into a program like Blender and export back out as fbx. Then when you get the results from mixamo, bring them back into Blender and export back out as glTF or glb to make them compatible with the hosts we provide. I have tried this process myself and it works well, and mixamo's library of animations is pretty extensive. Hope this helps.

**Comment by mikaelwozniak** [comment]
thanks a lot!

**Comment by belopot** [comment]
@c-morten  I added walking animation from mixamo, but I'm getting this issue
![image](https://user-images.githubusercontent.com/46432435/164786045-b39f1544-3952-46ad-9809-dbfc16db359d.png)

I uploaded Luke.gltf into mixamo and assigned walking animation and exported it into fbx. And then I opened the fbx in blender and exported it into glb file. 

Could you please give me an advice?
