### ISSUE TITLE
Support for Offscreen Canvas

### ISSUE THREAD

**Issue by jkeys-ecg-nmsu** [aws-samples/amazon-sumerian-hosts#34]
Since Babylon 4.1, the Offscreen Canvas API is supported to allow multithreading with Babylon programs. 

https://doc.babylonjs.com/divingDeeper/scene/offscreenCanvas

This does not seem to be supported by this repository, as the Messenger class uses the `window` object for dispatching events. https://github.com/aws-samples/amazon-sumerian-hosts/blob/mainline/src/core/Messenger.js#L26

Is there a reason that this library needs to use the `window` for communication, as opposed to another pubsub implementation like the [Node events library](https://www.npmjs.com/package/events)?

**Comment by jkerste** [comment]
Hey @jkeys-ecg-nmsu, there is no intention at this time to incorporate multithreading support into this repo. That said there is no inherent reason the Messenger class is required to use `window`.
