### ISSUE TITLE
Mismatch on imported and exported gltf/glb files? Help!

### ISSUE THREAD

**Issue by bobsi101** [aws-samples/amazon-sumerian-hosts#39]
With intentions to edit the avatar and animations I am trying to dissect how these character and animation files are made? Or how I can edit them? 
As a test I imported the character into blender and exported straight away back into gltf/glb format. 
Results:
- the .bin file completely different, 
- the file size has increased from 50kb to 30mb
- the mesh is completely distorted after re-export (animations still work to an extent)
Any help would be much appreciated thank you!

**Comment by crowers** [comment]
Hi @bobsi101 Did you find a solution for this? we have imported the sample gltf characters into blender and re-exported and the mesh is distorted. Spent hours looking for an answer, so any guidance would be much appreciated!

**Comment by kzzztkt** [comment]
> Hi @bobsi101 Did you find a solution for this? we have imported the sample gltf characters into blender and re-exported and the mesh is distorted. Spent hours looking for an answer, so any guidance would be much appreciated!

Hi @crowers. Yes. I discovered it was the animations that were distorting the character as taking them into other applications did not give such a result. So the solution is to also import the animations that AWS put on the avatar into blender then export them back out to replace the original file (same process as the avatar). This solved the the distortion issue. Hope this helps :)
