### ISSUE TITLE
General Question: What are the range of projects that this library can be used under the current license?

### ISSUE THREAD

**Issue by inglesuniversal** [aws-samples/amazon-sumerian-hosts#50]
I run an educational institution and these characters would be a great tool for our Language Learning Centers and Online Classes.

Best regards

**Comment by SavagePencil** [comment]
Take a look at the license, which details permissions, and verify if it fits your needs:  https://github.com/aws-samples/amazon-sumerian-hosts/blob/mainline/LICENSE

**Comment by ajorg-aws** [comment]
@SavagePencil The LICENSE you pointed to is for the code in the repo. The license for the characters is at https://github.com/aws-samples/amazon-sumerian-hosts/blob/mainline/examples/assets/LICENSE
